"""Experiment-side utilities for the BlackOut reinforcement-learning project."""

from .batching import ObservationBatch, canonical_agents, stack_observations, team_agents
from .env import ContractBlackOutEnv
from .reward import ScoreDeltaEvent, ScoreDeltaRewardTracker
from .navigation import AStarPlanner, PathNotFound, WaypointFollower, grid_line, path_cost
from .policy import ActionPolicy, FixedDirectionPolicy, NoOpPolicy, RandomPolicy
from .semantic_map import (
    DEFAULT_RESOLUTION_SCALE,
    DecodedSemanticMap,
    GridCell,
    SemanticMapDecoder,
    SemanticPoint,
    cell_center_normalized,
    normalized_to_cell,
    normalized_to_pixel,
    pixel_to_normalized,
)
from .model_contract import (
    ACTION_DIRECTIONS,
    CHECKPOINT_SCHEMA_VERSION,
    ActorCriticOutput,
    CanonicalTeamModel,
    ReferenceActorCritic,
    SubmissionPolicy,
    TeamModelInput,
    categorical_action,
    checkpoint_payload,
    deterministic_action,
    load_checkpoint,
    save_checkpoint,
    team_model_input,
    validate_checkpoint,
)
from .observation import (
    GRAPHIC_CHANNEL_NAMES,
    VECTOR_SIZE,
    GraphicObservation,
    VectorObservation,
    hwc_to_chw,
    parse_graphic,
    parse_vector,
)

__all__ = [
    "GRAPHIC_CHANNEL_NAMES",
    "DEFAULT_RESOLUTION_SCALE",
    "ACTION_DIRECTIONS",
    "CHECKPOINT_SCHEMA_VERSION",
    "ActorCriticOutput",
    "ActionPolicy",
    "AStarPlanner",
    "CanonicalTeamModel",
    "DecodedSemanticMap",
    "FixedDirectionPolicy",
    "GridCell",
    "VECTOR_SIZE",
    "GraphicObservation",
    "ObservationBatch",
    "NoOpPolicy",
    "PathNotFound",
    "RandomPolicy",
    "ContractBlackOutEnv",
    "ScoreDeltaEvent",
    "ScoreDeltaRewardTracker",
    "ReferenceActorCritic",
    "SubmissionPolicy",
    "TeamModelInput",
    "SemanticMapDecoder",
    "SemanticPoint",
    "VectorObservation",
    "canonical_agents",
    "cell_center_normalized",
    "categorical_action",
    "checkpoint_payload",
    "deterministic_action",
    "hwc_to_chw",
    "grid_line",
    "normalized_to_cell",
    "normalized_to_pixel",
    "parse_graphic",
    "parse_vector",
    "path_cost",
    "pixel_to_normalized",
    "load_checkpoint",
    "save_checkpoint",
    "stack_observations",
    "team_agents",
    "team_model_input",
    "validate_checkpoint",
    "WaypointFollower",
]
