"""Experiment-side utilities for the BlackOut reinforcement-learning project."""

from .batching import ObservationBatch, canonical_agents, stack_observations, team_agents
from .env import ContractBlackOutEnv
from .reward import ScoreDeltaEvent, ScoreDeltaRewardTracker
from .coordination import (
    StuckDetector,
    StuckEvent,
    TaskAssignment,
    assignment_targets,
    greedy_path_assignment,
)
from .navigation import AStarPlanner, PathNotFound, WaypointFollower, grid_line, path_cost
from .policy import ActionPolicy, FixedDirectionPolicy, NoOpPolicy, RandomPolicy
from .semantic_map import (
    DEFAULT_RESOLUTION_SCALE,
    DecodedSemanticMap,
    GridCell,
    SemanticMapDecoder,
    SemanticPoint,
    cell_center_normalized,
    normalized_to_cell,
    normalized_to_pixel,
    pixel_to_normalized,
)
from .team_state import (
    DEFAULT_ROLES,
    Role,
    TeamSnapshot,
    TeamStateTracker,
    UnitState,
    default_roles,
)
from .trajectory import (
    GRAPHIC_ENCODING,
    TRAJECTORY_SCHEMA_VERSION,
    ScriptedTrajectoryRecorder,
    decode_graphic,
    encode_graphic,
)
from .scripted_fsm import (
    BATTERY_ITEM_ID,
    CARRIER_CLASS_ID,
    CARRIER_SHRINE_BY_TEAM,
    COLLECTOR_CLASS_ID,
    HUNTER_CLASS_ID,
    HUNTER_SHRINE_CELLS,
    CarrierPhase,
    FSMDecision,
    GuardPhase,
    ScriptedTeamController,
    WorkerPhase,
    battery_cells_from_graphic,
    carrier_shrine_cell,
    farthest_reachable_cell,
    nearest_reachable_cell,
    neutral_battery_cells,
    select_evasion_target,
)
from .model_contract import (
    ACTION_DIRECTIONS,
    CHECKPOINT_SCHEMA_VERSION,
    ActorCriticOutput,
    CanonicalTeamModel,
    ReferenceActorCritic,
    SubmissionPolicy,
    TeamModelInput,
    categorical_action,
    checkpoint_payload,
    deterministic_action,
    load_checkpoint,
    save_checkpoint,
    team_model_input,
    validate_checkpoint,
)
from .observation import (
    GRAPHIC_CHANNEL_NAMES,
    VECTOR_SIZE,
    GraphicObservation,
    VectorObservation,
    hwc_to_chw,
    parse_graphic,
    parse_vector,
)

__all__ = [
    "GRAPHIC_CHANNEL_NAMES",
    "DEFAULT_RESOLUTION_SCALE",
    "DEFAULT_ROLES",
    "ACTION_DIRECTIONS",
    "CHECKPOINT_SCHEMA_VERSION",
    "ActorCriticOutput",
    "ActionPolicy",
    "BATTERY_ITEM_ID",
    "AStarPlanner",
    "CanonicalTeamModel",
    "CARRIER_CLASS_ID",
    "CARRIER_SHRINE_BY_TEAM",
    "COLLECTOR_CLASS_ID",
    "DecodedSemanticMap",
    "FixedDirectionPolicy",
    "FSMDecision",
    "GridCell",
    "GRAPHIC_ENCODING",
    "GuardPhase",
    "HUNTER_CLASS_ID",
    "HUNTER_SHRINE_CELLS",
    "VECTOR_SIZE",
    "GraphicObservation",
    "ObservationBatch",
    "NoOpPolicy",
    "PathNotFound",
    "RandomPolicy",
    "Role",
    "ContractBlackOutEnv",
    "ScoreDeltaEvent",
    "ScoreDeltaRewardTracker",
    "ReferenceActorCritic",
    "SubmissionPolicy",
    "TeamModelInput",
    "SemanticMapDecoder",
    "SemanticPoint",
    "ScriptedTrajectoryRecorder",
    "ScriptedTeamController",
    "StuckDetector",
    "StuckEvent",
    "TRAJECTORY_SCHEMA_VERSION",
    "TaskAssignment",
    "TeamSnapshot",
    "TeamStateTracker",
    "UnitState",
    "WorkerPhase",
    "battery_cells_from_graphic",
    "CarrierPhase",
    "VectorObservation",
    "canonical_agents",
    "assignment_targets",
    "cell_center_normalized",
    "carrier_shrine_cell",
    "categorical_action",
    "checkpoint_payload",
    "deterministic_action",
    "decode_graphic",
    "default_roles",
    "encode_graphic",
    "farthest_reachable_cell",
    "hwc_to_chw",
    "grid_line",
    "greedy_path_assignment",
    "normalized_to_cell",
    "normalized_to_pixel",
    "parse_graphic",
    "parse_vector",
    "path_cost",
    "pixel_to_normalized",
    "load_checkpoint",
    "save_checkpoint",
    "stack_observations",
    "nearest_reachable_cell",
    "neutral_battery_cells",
    "select_evasion_target",
    "team_agents",
    "team_model_input",
    "validate_checkpoint",
    "WaypointFollower",
]
